kumuluzee:
  name: rso-images
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/ImagesDS
      # kubernetes: change connection-url, example -> jdbc:postgresql://sl-eu-gb-p00.dblayer.com:15468/compose
      connection-url: jdbc:postgresql://localhost:5432/image
      # kubernetes: comment username/password
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
app-properties:
  external-services:
    enabled: true