kumuluzee:
  name: rso-images
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/ImagesDS
      connection-url: jdbc:postgresql://localhost:5433/image
      username: dbuser
      password: postgres
      max-pool-size: 20